# Generated by Django 2.0 on 2018-02-02 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerymodel',
            name='image',
        ),
    ]
