# Generated by Django 2.0 on 2018-02-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20180202_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
