# Generated by Django 2.0 on 2018-01-27 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180127_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.TagModel'),
        ),
    ]
