# Generated by Django 2.0 on 2018-01-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postmodel_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='tag',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='tag',
            field=models.ManyToManyField(to='blog.TagModel'),
        ),
    ]
