# Generated by Django 2.0 on 2018-01-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180129_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='picture',
            field=models.ImageField(upload_to='.blog/static/blog/upload/'),
        ),
    ]
