# Generated by Django 2.0 on 2018-01-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180129_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='picture',
            field=models.ImageField(upload_to='./upload/', verbose_name='配图'),
        ),
    ]
