# Generated by Django 2.0 on 2018-01-29 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180129_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='picture',
            new_name='image',
        ),
    ]
