# Generated by Django 2.0 on 2018-02-02 03:05

import gallery.files_handle
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_postmodel_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=gallery.files_handle.ThumbnailImageField(upload_to='./article/'),
        ),
    ]
